### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by sebastianfaulhaber** [AtomLinter/linter-docker#5]
Hi there,
unfortunately I cannot get the plugin to work. Here's what I've done so far:

npm install -g dockerlint
npm install -g atom-linter
apm install linter-docker

I am still unsure about the following:
1. Which path do I have to enter for "Some executable path"?
2. How does my Dockerfile has to be named in order to be picked up by the linter? So does "Dockerfile" work for example?

Thanks a lot,
Sebastian

**Comment by johnwebbcole** [comment]
Make sure the grammar type is set to Dockerfile.

**Comment by sebastianfaulhaber** [comment]
Hi John,

which package do I need to install? This one: https://atom.io/packages/language-docker ?

Cheers,
Sebastian

**Comment by Arcanemagus** [comment]
@sebastianfaulhaber that one would do just fine :wink:.

**Comment by Arcanemagus** [comment]
Also you would put the output of `which dockerlint` (Or `where.exe dockerlint` on Windows) into the Executable Path setting if you need to. By default it will use one that is bundled with the package though so that shouldn't be necessary.

**Comment by Arcanemagus** [comment]
Oh, and you don't need `atom-linter` installed globally.

**Comment by sebastianfaulhaber** [comment]
Ok...so I've installed "language-docker" and the syntax highlighting seems to work now. I've also checked that the linting works in general (with the JSON linter). However...nothing happens when I open my 'Dockerfile'.

Any further ideas?

**Comment by Arcanemagus** [comment]
Doesn't appear to be working for me either, investigating.

**Comment by Arcanemagus** [comment]
`dockerlint` itself is either reporting a file with many issues as OK, or crashing...

**Comment by Arcanemagus** [comment]
Is it working for you from the command line @sebastianfaulhaber?

**Comment by sebastianfaulhaber** [comment]
yes...`dockerlint` works fine from the command line.

**Comment by Arcanemagus** [comment]
@sebastianfaulhaber Can you open Atom's developer tools and put a breakpoint [here](https://github.com/AtomLinter/linter-docker/blob/0.1.2/lib/init.coffee#L31) and see what the contents of `output` are?

@johnwebbcole You'll have to verify this is working properly, `dockerlint` itself is failing on both Ubuntu and Windows for me.

**Comment by sebastianfaulhaber** [comment]
@Arcanemagus Can you give me a hint on how to do this...I have only scratched the surface of atom yet.

**Comment by Arcanemagus** [comment]
0. View -> Developer -> Toggle developer tools
0. Locate the `linter-docker/lib` folder inside the `.atom/packages` folder and double click on `init.coffee`
0. Click the line that looks like the one I linked, it _should_ be 31, but Atom sometimes shows the recompiled version there so you may need to look around.
0. Try to lint a docker file, it should stop execution and `output` should be listed in the Local scope on the right hand side of the window.

**Comment by sebastianfaulhaber** [comment]
I've added a watch
filePath: --> fully qualified path to my Dockerfile...looks ok.
output: "" --> does not seem to be ok.

**Comment by sebastianfaulhaber** [comment]
Ok...so I've debugged a little more:
The ruleset of "dockerlint" was not complaining about obvious syntax errors I included. It always reported that everything is OK.

When I put in an "ADD" then I'll get a warning displayed. So the package itself seems to be working.

**Comment by Arcanemagus** [comment]
I was getting either "OK", or crashes from their [test files](https://github.com/RedCoolBeans/dockerlint/tree/v0.1.3/test/dockerfiles).

**Comment by sebastianfaulhaber** [comment]
I've checked their testfiles as well:

INFO: line_continuations is OK.
INFO: line_count is OK.

The other two produce stacktraces:

ypeError: Cannot read property 'instruction' of undefined
    at Object.exports.from_first (/usr/local/lib/node_modules/dockerlint/lib/checks.js:41:14)
    at Object.exports.run (/usr/local/lib/node_modules/dockerlint/lib/cli.js:47:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/dockerlint/bin/dockerlint.js:17:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/dockerlint/bin/dockerlint.js:19:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

**Comment by chrisLeeTW** [comment]
I had same situation until I manually update dockerlint version up to 0.2.0 in linter-docker node_modules.

**Comment by daashayani** [comment]
[root@dockerdst ubuntu-master]# dockerlint -f  /root/nginx-master/Dockerfile -r ./rules.yaml
check: from_first
check: no_empty_tag
check: no_empty_digest
check: json_array_brackets
check: json_array_even_quotes
check: json_array_format
DEBUG:'Arg: ["nginx"]'
DEBUG:'Arg: ["/etc/nginx/sites-enabled"'
DEBUG:'Arg:  "/etc/nginx/certs"'
DEBUG:'Arg:  "/etc/nginx/conf.d"'
DEBUG:'Arg:  "/var/log/nginx"'
DEBUG:'Arg:  "/var/www/html"]'
check: recommended_exec_form
check: add
check: multiple_entries
check: sudo
check: absolute_workdir
check: onbuild_copyadd
check: onbuild_disallowed
check: label_no_empty_value

INFO: /root/nginx-master/Dockerfile is OK.

**Comment by daashayani** [comment]
dockerlint is not checking for other commands like RUN

**Comment by Arcanemagus** [comment]
@daashayani This is just a wrapper _around_ `dockerlint`, you should report issues with `dockerlint` over on [their repo](https://github.com/RedCoolBeans/dockerlint).

**Comment by Arcanemagus** [comment]
It looks like there were a few different issues reported here, several of which are likely fixed by #38. Once that gets released shortly if you are still experiencing problems please file a _new_ issue to track it.
